name: ItemsXL
main: de.erethon.itemsxl.ItemsXL
version: ${project.version}
author: Daniel Saukel
description: ${project.description}${buildNo}
website: ${project.url}
commands:
  itemsxl:
    description: ItemsXL core command.
    aliases: [ixl]
permissions:
  ixl.give.*:
    description: Get all IXL items.
    default: op
  ixl.info.*:
    description: Get information about all IXL items.
    default: true
  ixl.reload:
    description: Reload all config files.
    default: op
