name: ${project.name}
main: ${project.groupId}.${project.artifactId}.${project.name}
version: ${project.version}${buildNo}
author: Daniel Saukel
description: ${project.description}
website: ${project.url}
commands:
  itemsxl:
    description: ItemsXL core command.
    aliases: [ixl]
api-version: 1.13
